#!/bin/bash
#Usage: secret filename

if [ $# -lt 1 ]; then
    echo "Usage: secret <filename>"
    exit 1
fi

echo "Enter passphrase: "
read -s PASSPHRASE
FILE=$1

ENCRYPTED_HEADER="Salted__"
IS_ENCRYPTED=$(head -c 8 "$FILE" | grep "$ENCRYPTED_HEADER")

if [ "$IS_ENCRYPTED" ]; then
    openssl enc -aes-256-cbc -d -in "$FILE" -out "${FILE}.dec" -pass pass:"$PASSPHRASE" 2>/dev/null
    if [ $? -eq 0 ]; then
        mv "${FILE}.dec" "$FILE"
        echo "File decrypted successfully."
    else
        echo "Failed to decrypt the file."
        rm "${FILE}.dec"
    fi
else
    openssl enc -aes-256-cbc -in "$FILE" -out "${FILE}.enc" -pass pass:"$PASSPHRASE" 2>/dev/null
    if [ $? -eq 0 ]; then
        mv "${FILE}.enc" "$FILE"
        echo "File encrypted successfully."
    else
        echo "Failed to encrypt the file."
        rm "${FILE}.enc"
    fi
fi
